# SimpleRTP config file

# Whether players will be randomly teleported automatically upon their first time joining
random-teleport-on-first-join: true

respawn-nearby-on-death: false

maxY: 128

blacklisted-biomes:
  - desert
  - ocean
  - warm_ocean
  - deep_ocean
  - frozen_ocean
  - deep_frozen_ocean
  - lukewarm_ocean
  - deep_lukewarm_ocean
  - cold_ocean
  - deep_cold_ocean
  - frozen_ocean
  - cold_ocean
  - lukewarm_ocean
  - warm_ocean
  - snowy_plains
  - river

blacklisted-blocks:
  - leaves

regions:
  default:
    areas:
      - minX: -100
        maxX: 100
        minZ: -100
        maxZ: 100
