name: SimpleRTP
version: '${version}'
main: net.earthmc.simplertp.SimpleRTP
api-version: '1.20'
authors: [ Warriorrr ]
contributors: [Veyronity]
folia-supported: true
softdepend:
  - Towny

commands:
  rtp:
    description: Teleports the player to a random location.

permissions:
  simplertp.command.rtp:
    description: Gives players access to the /rtp command
    default: op

  simplertp.command.rtp.*:
    default: op
    children:
      simplertp.command.rtp.others: true
      simplertp.command.rtp.reload: true
      simplertp.command.rtp.debug: true

  simplertp.command.rtp.others:
    default: op
    children:
      simplertp.command.rtp: true

  simplertp.teleport.nowarmup:
    default: false
